name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: npm

      - name: Show environment versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: npm run ci:quality

      - name: Run linting
        run: npm run lint

      - name: Run test placeholder
        run: echo "Running tests ------>>>"

      - name: Build project
        run: npm run build
